apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nebula-exporter.name" . }}
  labels:
    {{- include "nebula-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nebula-exporter.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nebula-exporter.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "nebula-exporter.serviceAccountName" . }}
      containers:
        - name: nebula-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--listen-address=0.0.0.0:{{ .Values.startUp.listenPort }}"
            - "--namespace={{ .Release.Namespace }}"
            - "--cluster={{ .Values.cluster }}"
            - "--cluster-label-key={{ .Values.clusterLabelKey }}"
            - "--selector={{ .Values.selector }}"
            - "--graph-port-name={{ .Values.graphPortName }}"
            - "--meta-port-name={{ .Values.metaPortName }}"
            - "--storage-port-name={{ .Values.storagePortName }}"
            - "--max-request={{ .Values.startUp.maxRequests }}"
          ports:
            - name: exporter-port
              containerPort: {{ .Values.startUp.listenPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.startUp.listenPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
        affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
        tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}