{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nebula-exporter.name" . }}
  labels:
  {{- toYaml .Values.serviceMonitor.prometheusServiceMatchLabels | nindent 4 }}
    {{- include "nebula-exporter.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nebula-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: exporter-port
{{- end }}