apiVersion: v1
entries:
  nebula-exporter:
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2021-06-21T12:15:40.022657+08:00"
    description: Nebula Graph stats exporter for prometheus
    digest: 8d80e3c86b9f098ef546901b57f3bc7ee01e23f31884e671e0240d47a48fcbe3
    home: https://nebula-graph.io
    icon: https://github.com/vesoft-inc/nebula/raw/master/docs/logo.png
    keywords:
    - kubernetes
    - exporter
    - prometheus
    - nebula
    - graph
    maintainers:
    - email: kevin.qiao@vesoft.com
      name: kevin
      url: https://github.com/MegaByte875
    - email: kenshin.liu@vesoft.com
      name: kenshin
      url: https://github.com/kqzh
    - email: vee.zhang@vesoft.com
      name: Vee Zhang
      url: https://github.com/veezhang
    name: nebula-exporter
    sources:
    - https://github.com/vesoft-inc/nebula
    urls:
    - https://vesoft-inc.github.io/nebula-stats-exporter/charts/nebula-exporter-0.2.0.tgz
    version: 0.2.0
generated: "2021-06-21T12:15:40.021997+08:00"
